-- =============================================================================
-- Seed: SQL Text Task Bank (25 tasks)
-- Scenario: School management system with students, courses, assignments, submissions
--
-- Shared sample database schema used across all SQL_TEXT tasks:
--   students(student_id, name, grade_level, class_section)
--   courses(course_id, course_name, teacher_name)
--   enrollments(enrollment_id, student_id, course_id, enrolled_at)
--   assignments(assignment_id, course_id, title, max_score)
--   submissions(submission_id, student_id, assignment_id, score, submitted_at)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Shared JSON fragments (stored as task-level metadata per task)
-- ---------------------------------------------------------------------------

do $$ begin end $$; -- no-op: SQL_TEXT tasks insert directly below

-- ---------------------------------------------------------------------------
-- Task inserts
-- ---------------------------------------------------------------------------

insert into public.mst_tasks (
  task_code, task_title, task_type, difficulty_level,
  task_type_id, difficulty_level_id, skill_area_id, task_status_id,
  task_status, is_active, estimated_time_seconds,
  instruction_text, expected_sql,
  database_schema_json, sample_data_json, expected_output_json,
  grading_rules_json, hint_json, answer_format_json, metadata_json
)
values

-- ── Task 001 ────────────────────────────────────────────────────────────────
('SQL_TEXT_001',
 'SELECT all students',
 'sql_text', 'easy',
 1, 1, 1, 4,
 'published', true, 120,
 'Write a SQL query to select all columns from the students table.',
 'SELECT * FROM students;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"}]}',
 '[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"}]',
 '{"check_type":"exact_match","ignore_column_order":true,"ignore_row_order":true}',
 '{"hints":["Use SELECT * to select all columns","Specify the table name after FROM"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"basic_select","bloom_level":"remember"}'),

-- ── Task 002 ────────────────────────────────────────────────────────────────
('SQL_TEXT_002',
 'SELECT specific columns from students',
 'sql_text', 'easy',
 1, 1, 1, 4,
 'published', true, 120,
 'Write a query to select only the name and grade_level columns from the students table.',
 'SELECT name, grade_level FROM students;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6},{"student_id":2,"name":"Bob","grade_level":6},{"student_id":3,"name":"Charlie","grade_level":5}]}',
 '[{"name":"Alice","grade_level":6},{"name":"Bob","grade_level":6},{"name":"Charlie","grade_level":5}]',
 '{"check_type":"exact_match","ignore_row_order":true,"required_columns":["name","grade_level"]}',
 '{"hints":["List column names separated by commas after SELECT"]}',
 '{"type":"table","columns":["name","grade_level"]}',
 '{"topic":"column_selection","bloom_level":"remember"}'),

-- ── Task 003 ────────────────────────────────────────────────────────────────
('SQL_TEXT_003',
 'Filter students by grade level',
 'sql_text', 'easy',
 1, 1, 2, 4,
 'published', true, 120,
 'Write a query to select all students where grade_level equals 6.',
 'SELECT * FROM students WHERE grade_level = 6;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":4,"name":"Diana","grade_level":6,"class_section":"B"}]}',
 '[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":4,"name":"Diana","grade_level":6,"class_section":"B"}]',
 '{"check_type":"exact_match","ignore_row_order":true}',
 '{"hints":["Use WHERE to filter rows","Use = for equality comparison"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"where_filter","bloom_level":"understand"}'),

-- ── Task 004 ────────────────────────────────────────────────────────────────
('SQL_TEXT_004',
 'Filter students by class section',
 'sql_text', 'easy',
 1, 1, 2, 4,
 'published', true, 120,
 'Write a query to find all students in class_section ''A''.',
 'SELECT * FROM students WHERE class_section = ''A'';',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":5,"name":"Eve","grade_level":5,"class_section":"A"}]}',
 '[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":5,"name":"Eve","grade_level":5,"class_section":"A"}]',
 '{"check_type":"exact_match","ignore_row_order":true}',
 '{"hints":["Wrap string values in single quotes"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"where_string_filter","bloom_level":"understand"}'),

-- ── Task 005 ────────────────────────────────────────────────────────────────
('SQL_TEXT_005',
 'Sort students by name',
 'sql_text', 'easy',
 1, 1, 3, 4,
 'published', true, 120,
 'Write a query to select all students ordered by name in ascending order.',
 'SELECT * FROM students ORDER BY name ASC;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"}]}',
 '[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"}]',
 '{"check_type":"exact_match","ignore_row_order":false}',
 '{"hints":["Use ORDER BY followed by the column name","ASC means ascending (A to Z)"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"order_by","bloom_level":"understand"}'),

-- ── Task 006 ────────────────────────────────────────────────────────────────
('SQL_TEXT_006',
 'Sort students by grade level descending',
 'sql_text', 'easy',
 1, 1, 3, 4,
 'published', true, 120,
 'Write a query to select name and grade_level from students, ordered by grade_level descending.',
 'SELECT name, grade_level FROM students ORDER BY grade_level DESC;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6},{"student_id":2,"name":"Bob","grade_level":6},{"student_id":3,"name":"Charlie","grade_level":5}]}',
 '[{"name":"Alice","grade_level":6},{"name":"Bob","grade_level":6},{"name":"Charlie","grade_level":5}]',
 '{"check_type":"exact_match","ignore_row_order":false,"required_columns":["name","grade_level"]}',
 '{"hints":["DESC means descending (highest first)"]}',
 '{"type":"table","columns":["name","grade_level"]}',
 '{"topic":"order_by_desc","bloom_level":"understand"}'),

-- ── Task 007 ────────────────────────────────────────────────────────────────
('SQL_TEXT_007',
 'COUNT all students',
 'sql_text', 'easy',
 1, 1, 11, 4,
 'published', true, 120,
 'Write a query to count the total number of students.',
 'SELECT COUNT(*) AS total_students FROM students;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1},{"student_id":2},{"student_id":3},{"student_id":4},{"student_id":5}]}',
 '[{"total_students":5}]',
 '{"check_type":"exact_match","ignore_column_alias":true}',
 '{"hints":["COUNT(*) counts all rows","Use AS to give the result column a name"]}',
 '{"type":"table","columns":["total_students"]}',
 '{"topic":"count_aggregate","bloom_level":"understand"}'),

-- ── Task 008 ────────────────────────────────────────────────────────────────
('SQL_TEXT_008',
 'COUNT students per grade level',
 'sql_text', 'medium',
 1, 2, 6, 4,
 'published', true, 180,
 'Write a query to count how many students are in each grade_level. Show grade_level and the count.',
 'SELECT grade_level, COUNT(*) AS student_count FROM students GROUP BY grade_level;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"grade_level":6,"count":3},{"grade_level":5,"count":2}]}',
 '[{"grade_level":5,"student_count":2},{"grade_level":6,"student_count":3}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["Use GROUP BY to group rows","COUNT(*) counts rows in each group"]}',
 '{"type":"table","columns":["grade_level","student_count"]}',
 '{"topic":"group_by","bloom_level":"apply"}'),

-- ── Task 009 ────────────────────────────────────────────────────────────────
('SQL_TEXT_009',
 'JOIN students and submissions',
 'sql_text', 'medium',
 1, 2, 4, 4,
 'published', true, 180,
 'Write a query to show each student''s name and their score from the submissions table. Use an INNER JOIN.',
 'SELECT s.name, sub.score FROM students s INNER JOIN submissions sub ON s.student_id = sub.student_id;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]},{"name":"submissions","columns":["submission_id","student_id","assignment_id","score","submitted_at"]}]}',
 '{"students":[{"student_id":1,"name":"Alice"},{"student_id":2,"name":"Bob"}],"submissions":[{"submission_id":1,"student_id":1,"assignment_id":1,"score":95},{"submission_id":2,"student_id":2,"assignment_id":1,"score":78}]}',
 '[{"name":"Alice","score":95},{"name":"Bob","score":78}]',
 '{"check_type":"exact_match","ignore_row_order":true,"required_columns":["name","score"]}',
 '{"hints":["Use JOIN ... ON to link tables by a shared key","student_id appears in both tables"]}',
 '{"type":"table","columns":["name","score"]}',
 '{"topic":"inner_join","bloom_level":"apply"}'),

-- ── Task 010 ────────────────────────────────────────────────────────────────
('SQL_TEXT_010',
 'JOIN three tables: students, submissions, assignments',
 'sql_text', 'medium',
 1, 2, 5, 4,
 'published', true, 180,
 'Show each student name, assignment title, and their score. Join students, submissions, and assignments.',
 'SELECT st.name, a.title, sub.score FROM students st INNER JOIN submissions sub ON st.student_id = sub.student_id INNER JOIN assignments a ON sub.assignment_id = a.assignment_id;',
 '{"tables":[{"name":"students","columns":["student_id","name"]},{"name":"assignments","columns":["assignment_id","course_id","title","max_score"]},{"name":"submissions","columns":["submission_id","student_id","assignment_id","score"]}]}',
 '{"students":[{"student_id":1,"name":"Alice"},{"student_id":2,"name":"Bob"}],"assignments":[{"assignment_id":1,"title":"SELECT Query"}],"submissions":[{"submission_id":1,"student_id":1,"assignment_id":1,"score":95},{"submission_id":2,"student_id":2,"assignment_id":1,"score":78}]}',
 '[{"name":"Alice","title":"SELECT Query","score":95},{"name":"Bob","title":"SELECT Query","score":78}]',
 '{"check_type":"exact_match","ignore_row_order":true,"required_columns":["name","title","score"]}',
 '{"hints":["Chain multiple JOINs one after another","Each JOIN needs its own ON condition"]}',
 '{"type":"table","columns":["name","title","score"]}',
 '{"topic":"multi_join","bloom_level":"apply"}'),

-- ── Task 011 ────────────────────────────────────────────────────────────────
('SQL_TEXT_011',
 'AVG score per student',
 'sql_text', 'medium',
 1, 2, 11, 4,
 'published', true, 180,
 'Write a query to find the average score for each student. Show student_id and average score.',
 'SELECT student_id, AVG(score) AS avg_score FROM submissions GROUP BY student_id;',
 '{"tables":[{"name":"submissions","columns":["submission_id","student_id","assignment_id","score","submitted_at"]}]}',
 '{"submissions":[{"submission_id":1,"student_id":1,"score":95},{"submission_id":3,"student_id":1,"score":85},{"submission_id":2,"student_id":2,"score":78}]}',
 '[{"student_id":1,"avg_score":90},{"student_id":2,"avg_score":78}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["AVG() calculates the mean value","GROUP BY student_id groups each student separately"]}',
 '{"type":"table","columns":["student_id","avg_score"]}',
 '{"topic":"avg_aggregate","bloom_level":"apply"}'),

-- ── Task 012 ────────────────────────────────────────────────────────────────
('SQL_TEXT_012',
 'MAX and MIN score',
 'sql_text', 'easy',
 1, 1, 11, 4,
 'published', true, 120,
 'Write a query to find the highest and lowest score from the submissions table.',
 'SELECT MAX(score) AS max_score, MIN(score) AS min_score FROM submissions;',
 '{"tables":[{"name":"submissions","columns":["submission_id","student_id","assignment_id","score"]}]}',
 '{"submissions":[{"score":95},{"score":78},{"score":85},{"score":90},{"score":72},{"score":88},{"score":65}]}',
 '[{"max_score":95,"min_score":65}]',
 '{"check_type":"exact_match","ignore_column_alias":true}',
 '{"hints":["MAX() returns the largest value","MIN() returns the smallest value"]}',
 '{"type":"table","columns":["max_score","min_score"]}',
 '{"topic":"max_min_aggregate","bloom_level":"understand"}'),

-- ── Task 013 ────────────────────────────────────────────────────────────────
('SQL_TEXT_013',
 'Filter groups with HAVING',
 'sql_text', 'medium',
 1, 2, 7, 4,
 'published', true, 180,
 'Write a query to show grade_level groups that have more than 2 students.',
 'SELECT grade_level, COUNT(*) AS student_count FROM students GROUP BY grade_level HAVING COUNT(*) > 2;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"grade_level":6,"count":3},{"grade_level":5,"count":2}]}',
 '[{"grade_level":6,"student_count":3}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["HAVING filters groups after GROUP BY","Use HAVING instead of WHERE when filtering aggregated results"]}',
 '{"type":"table","columns":["grade_level","student_count"]}',
 '{"topic":"having_clause","bloom_level":"apply"}'),

-- ── Task 014 ────────────────────────────────────────────────────────────────
('SQL_TEXT_014',
 'WHERE with AND condition',
 'sql_text', 'easy',
 1, 1, 2, 4,
 'published', true, 120,
 'Write a query to find students who are in grade_level 6 AND class_section ''A''.',
 'SELECT * FROM students WHERE grade_level = 6 AND class_section = ''A'';',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"}]}',
 '[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"}]',
 '{"check_type":"exact_match","ignore_row_order":true}',
 '{"hints":["Use AND to combine two conditions","Both conditions must be true"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"where_and","bloom_level":"understand"}'),

-- ── Task 015 ────────────────────────────────────────────────────────────────
('SQL_TEXT_015',
 'WHERE with OR condition',
 'sql_text', 'easy',
 1, 1, 2, 4,
 'published', true, 120,
 'Write a query to find students who are in grade_level 5 OR class_section ''B''.',
 'SELECT * FROM students WHERE grade_level = 5 OR class_section = ''B'';',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"},{"student_id":4,"name":"Diana","grade_level":6,"class_section":"B"},{"student_id":5,"name":"Eve","grade_level":5,"class_section":"A"}]}',
 '[{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"},{"student_id":4,"name":"Diana","grade_level":6,"class_section":"B"},{"student_id":5,"name":"Eve","grade_level":5,"class_section":"A"}]',
 '{"check_type":"exact_match","ignore_row_order":true}',
 '{"hints":["Use OR when either condition can be true"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"where_or","bloom_level":"understand"}'),

-- ── Task 016 ────────────────────────────────────────────────────────────────
('SQL_TEXT_016',
 'DISTINCT grade levels',
 'sql_text', 'easy',
 1, 1, 1, 4,
 'published', true, 120,
 'Write a query to list all distinct grade levels from the students table.',
 'SELECT DISTINCT grade_level FROM students;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"grade_level":6},{"grade_level":5}]}',
 '[{"grade_level":5},{"grade_level":6}]',
 '{"check_type":"exact_match","ignore_row_order":true}',
 '{"hints":["DISTINCT removes duplicate values from results"]}',
 '{"type":"table","columns":["grade_level"]}',
 '{"topic":"distinct","bloom_level":"understand"}'),

-- ── Task 017 ────────────────────────────────────────────────────────────────
('SQL_TEXT_017',
 'LIMIT number of rows',
 'sql_text', 'easy',
 1, 1, 1, 4,
 'published', true, 120,
 'Write a query to select only the first 3 students from the students table.',
 'SELECT * FROM students LIMIT 3;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"}]}',
 '[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"}]',
 '{"check_type":"row_count","expected_count":3}',
 '{"hints":["LIMIT n returns at most n rows"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"limit","bloom_level":"remember"}'),

-- ── Task 018 ────────────────────────────────────────────────────────────────
('SQL_TEXT_018',
 'SUM of scores per assignment',
 'sql_text', 'medium',
 1, 2, 11, 4,
 'published', true, 180,
 'Write a query to find the total (SUM) of scores for each assignment_id in the submissions table.',
 'SELECT assignment_id, SUM(score) AS total_score FROM submissions GROUP BY assignment_id;',
 '{"tables":[{"name":"submissions","columns":["submission_id","student_id","assignment_id","score"]}]}',
 '{"submissions":[{"assignment_id":1,"score":95},{"assignment_id":1,"score":78},{"assignment_id":2,"score":85}]}',
 '[{"assignment_id":1,"total_score":173},{"assignment_id":2,"total_score":85}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["SUM() adds all values in a column","GROUP BY assignment_id groups per assignment"]}',
 '{"type":"table","columns":["assignment_id","total_score"]}',
 '{"topic":"sum_group_by","bloom_level":"apply"}'),

-- ── Task 019 ────────────────────────────────────────────────────────────────
('SQL_TEXT_019',
 'LEFT JOIN to find students without submissions',
 'sql_text', 'medium',
 1, 2, 4, 4,
 'published', true, 180,
 'Write a query to find all students and their scores, including students who have no submissions. Use a LEFT JOIN.',
 'SELECT s.name, sub.score FROM students s LEFT JOIN submissions sub ON s.student_id = sub.student_id;',
 '{"tables":[{"name":"students","columns":["student_id","name"]},{"name":"submissions","columns":["submission_id","student_id","score"]}]}',
 '{"students":[{"student_id":1,"name":"Alice"},{"student_id":2,"name":"Bob"},{"student_id":3,"name":"Charlie"}],"submissions":[{"student_id":1,"score":95},{"student_id":2,"score":78}]}',
 '[{"name":"Alice","score":95},{"name":"Bob","score":78},{"name":"Charlie","score":null}]',
 '{"check_type":"exact_match","ignore_row_order":true,"required_columns":["name","score"]}',
 '{"hints":["LEFT JOIN keeps all rows from the left table","Rows with no match get NULL values"]}',
 '{"type":"table","columns":["name","score"]}',
 '{"topic":"left_join","bloom_level":"apply"}'),

-- ── Task 020 ────────────────────────────────────────────────────────────────
('SQL_TEXT_020',
 'Subquery: students with above-average score',
 'sql_text', 'medium',
 1, 2, 11, 4,
 'published', true, 180,
 'Write a query to find the names of students whose score is above the average score in submissions.',
 'SELECT s.name FROM students s WHERE s.student_id IN (SELECT student_id FROM submissions WHERE score > (SELECT AVG(score) FROM submissions));',
 '{"tables":[{"name":"students","columns":["student_id","name"]},{"name":"submissions","columns":["submission_id","student_id","score"]}]}',
 '{"students":[{"student_id":1,"name":"Alice"},{"student_id":2,"name":"Bob"},{"student_id":4,"name":"Diana"}],"submissions":[{"student_id":1,"score":95},{"student_id":2,"score":78},{"student_id":4,"score":90}]}',
 '[{"name":"Alice"},{"name":"Diana"}]',
 '{"check_type":"exact_match","ignore_row_order":true,"required_columns":["name"]}',
 '{"hints":["A subquery is a SELECT inside another SELECT","AVG() in the inner query calculates the overall average"]}',
 '{"type":"table","columns":["name"]}',
 '{"topic":"subquery","bloom_level":"analyze"}'),

-- ── Task 021 ────────────────────────────────────────────────────────────────
('SQL_TEXT_021',
 'CASE WHEN for score grade',
 'sql_text', 'hard',
 1, 3, 9, 4,
 'published', true, 300,
 'Write a query to show each submission''s score and a grade column: ''A'' if score >= 90, ''B'' if score >= 75, else ''C''.',
 'SELECT submission_id, score, CASE WHEN score >= 90 THEN ''A'' WHEN score >= 75 THEN ''B'' ELSE ''C'' END AS grade FROM submissions;',
 '{"tables":[{"name":"submissions","columns":["submission_id","student_id","assignment_id","score"]}]}',
 '{"submissions":[{"submission_id":1,"score":95},{"submission_id":2,"score":78},{"submission_id":3,"score":65}]}',
 '[{"submission_id":1,"score":95,"grade":"A"},{"submission_id":2,"score":78,"grade":"B"},{"submission_id":3,"score":65,"grade":"C"}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["CASE WHEN ... THEN ... END creates a conditional column","ELSE handles all remaining cases"]}',
 '{"type":"table","columns":["submission_id","score","grade"]}',
 '{"topic":"case_when","bloom_level":"apply"}'),

-- ── Task 022 ────────────────────────────────────────────────────────────────
('SQL_TEXT_022',
 'COUNT students per class section',
 'sql_text', 'easy',
 1, 1, 6, 4,
 'published', true, 120,
 'Write a query to count how many students are in each class_section.',
 'SELECT class_section, COUNT(*) AS student_count FROM students GROUP BY class_section;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"class_section":"A","count":3},{"class_section":"B","count":2}]}',
 '[{"class_section":"A","student_count":3},{"class_section":"B","student_count":2}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["GROUP BY class_section separates students by section"]}',
 '{"type":"table","columns":["class_section","student_count"]}',
 '{"topic":"group_by","bloom_level":"apply"}'),

-- ── Task 023 ────────────────────────────────────────────────────────────────
('SQL_TEXT_023',
 'ORDER BY multiple columns',
 'sql_text', 'medium',
 1, 2, 3, 4,
 'published', true, 180,
 'Write a query to select all students ordered by grade_level descending, then by name ascending.',
 'SELECT * FROM students ORDER BY grade_level DESC, name ASC;',
 '{"tables":[{"name":"students","columns":["student_id","name","grade_level","class_section"]}]}',
 '{"students":[{"student_id":1,"name":"Alice","grade_level":6,"class_section":"A"},{"student_id":4,"name":"Diana","grade_level":6,"class_section":"B"},{"student_id":2,"name":"Bob","grade_level":6,"class_section":"A"},{"student_id":3,"name":"Charlie","grade_level":5,"class_section":"B"},{"student_id":5,"name":"Eve","grade_level":5,"class_section":"A"}]}',
 '[{"name":"Alice","grade_level":6},{"name":"Bob","grade_level":6},{"name":"Diana","grade_level":6},{"name":"Charlie","grade_level":5},{"name":"Eve","grade_level":5}]',
 '{"check_type":"exact_match","ignore_row_order":false}',
 '{"hints":["List multiple sort columns separated by commas","Each column can have its own ASC or DESC"]}',
 '{"type":"table","columns":["student_id","name","grade_level","class_section"]}',
 '{"topic":"order_by_multi","bloom_level":"apply"}'),

-- ── Task 024 ────────────────────────────────────────────────────────────────
('SQL_TEXT_024',
 'JOIN with GROUP BY: submission count per student',
 'sql_text', 'hard',
 1, 3, 5, 4,
 'published', true, 300,
 'Show each student''s name and the number of submissions they have made. Include students with zero submissions.',
 'SELECT s.name, COUNT(sub.submission_id) AS submission_count FROM students s LEFT JOIN submissions sub ON s.student_id = sub.student_id GROUP BY s.student_id, s.name;',
 '{"tables":[{"name":"students","columns":["student_id","name"]},{"name":"submissions","columns":["submission_id","student_id"]}]}',
 '{"students":[{"student_id":1,"name":"Alice"},{"student_id":2,"name":"Bob"},{"student_id":3,"name":"Charlie"}],"submissions":[{"submission_id":1,"student_id":1},{"submission_id":2,"student_id":1},{"submission_id":3,"student_id":2}]}',
 '[{"name":"Alice","submission_count":2},{"name":"Bob","submission_count":1},{"name":"Charlie","submission_count":0}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true}',
 '{"hints":["COUNT(column) counts non-NULL values — a student with no submissions gets 0","LEFT JOIN preserves students with no submissions"]}',
 '{"type":"table","columns":["name","submission_count"]}',
 '{"topic":"join_group_by","bloom_level":"analyze"}'),

-- ── Task 025 ────────────────────────────────────────────────────────────────
('SQL_TEXT_025',
 'Full pipeline: top scorers per course',
 'sql_text', 'hard',
 1, 3, 5, 4,
 'published', true, 300,
 'Write a query to find the student name and their maximum score for each course. Show course_name, student name, and max_score. Join all necessary tables.',
 'SELECT c.course_name, s.name, MAX(sub.score) AS max_score FROM courses c INNER JOIN assignments a ON c.course_id = a.course_id INNER JOIN submissions sub ON a.assignment_id = sub.assignment_id INNER JOIN students s ON sub.student_id = s.student_id GROUP BY c.course_id, c.course_name, s.student_id, s.name;',
 '{"tables":[{"name":"students","columns":["student_id","name"]},{"name":"courses","columns":["course_id","course_name","teacher_name"]},{"name":"assignments","columns":["assignment_id","course_id","title","max_score"]},{"name":"submissions","columns":["submission_id","student_id","assignment_id","score"]}]}',
 '{"courses":[{"course_id":1,"course_name":"Database Basics"}],"assignments":[{"assignment_id":1,"course_id":1,"title":"SELECT Query"}],"students":[{"student_id":1,"name":"Alice"}],"submissions":[{"student_id":1,"assignment_id":1,"score":95}]}',
 '[{"course_name":"Database Basics","name":"Alice","max_score":95}]',
 '{"check_type":"exact_match","ignore_row_order":true,"ignore_column_alias":true,"required_columns":["course_name","name","max_score"]}',
 '{"hints":["Join 4 tables step by step","GROUP BY both course and student to get per-student-per-course max"]}',
 '{"type":"table","columns":["course_name","name","max_score"]}',
 '{"topic":"multi_join_aggregate","bloom_level":"analyze"}')

on conflict (task_code) do update set
  task_title              = excluded.task_title,
  task_type               = excluded.task_type,
  difficulty_level        = excluded.difficulty_level,
  task_type_id            = excluded.task_type_id,
  difficulty_level_id     = excluded.difficulty_level_id,
  skill_area_id           = excluded.skill_area_id,
  task_status_id          = excluded.task_status_id,
  task_status             = excluded.task_status,
  is_active               = excluded.is_active,
  estimated_time_seconds  = excluded.estimated_time_seconds,
  instruction_text        = excluded.instruction_text,
  expected_sql            = excluded.expected_sql,
  database_schema_json    = excluded.database_schema_json,
  sample_data_json        = excluded.sample_data_json,
  expected_output_json    = excluded.expected_output_json,
  grading_rules_json      = excluded.grading_rules_json,
  hint_json               = excluded.hint_json,
  answer_format_json      = excluded.answer_format_json,
  metadata_json           = excluded.metadata_json,
  updated_at              = now();
