-- =============================================================================
-- Seed: ER Diagram Task Bank (10 tasks)
-- Scenario: School management system design problems
--
-- expected_er_model_json stores a JSON object with:
--   entities: [{name, attributes: [{name, type, is_pk, is_fk, nullable}]}]
--   relationships: [{name, entity_a, entity_b, cardinality, participation}]
-- task_type = 'er_diagram', task_type_id = 4
-- =============================================================================

insert into public.mst_tasks (
  task_code, task_title, task_type, difficulty_level,
  task_type_id, difficulty_level_id, skill_area_id, task_status_id,
  task_status, is_active, estimated_time_seconds,
  instruction_text, expected_er_model_json,
  database_schema_json, sample_data_json, expected_output_json,
  grading_rules_json, hint_json, answer_format_json, metadata_json
)
values

-- ── Task ERD_001 ─────────────────────────────────────────────────────────────
('ERD_001',
 'Identify entities in a school system',
 'er_diagram', 'easy',
 4, 1, 19, 4,
 'published', true, 120,
 'A school tracks students and courses. Each student has a student ID, name, and grade level. Each course has a course ID and course name. Identify the two entities and their attributes.',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"grade_level","type":"INT","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"entity_match","required_entities":["Student","Course"],"check_primary_keys":true}',
 '{"hints":["Each noun that stores persistent data is usually an entity","The primary key uniquely identifies each row"]}',
 '{"type":"er_diagram","tool":"drag_and_drop_entity"}',
 '{"topic":"entity_identification","bloom_level":"remember"}'),

-- ── Task ERD_002 ─────────────────────────────────────────────────────────────
('ERD_002',
 'Draw a one-to-many relationship',
 'er_diagram', 'easy',
 4, 1, 20, 4,
 'published', true, 120,
 'A course can have many assignments, but each assignment belongs to exactly one course. Draw the relationship between Course and Assignment, and specify the cardinality.',
 '{"entities":[{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Assignment","attributes":[{"name":"assignment_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"title","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[{"name":"has","entity_a":"Course","entity_b":"Assignment","cardinality":"1:N","participation":"total"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"relationship_match","required_relationships":[{"entity_a":"Course","entity_b":"Assignment","cardinality":"1:N"}]}',
 '{"hints":["One course → many assignments = 1:N","The foreign key course_id lives in the many-side table"]}',
 '{"type":"er_diagram","tool":"relationship_connector"}',
 '{"topic":"one_to_many","bloom_level":"understand"}'),

-- ── Task ERD_003 ─────────────────────────────────────────────────────────────
('ERD_003',
 'Draw a many-to-many relationship',
 'er_diagram', 'easy',
 4, 1, 20, 4,
 'published', true, 120,
 'A student can enroll in many courses, and a course can have many students. Draw the many-to-many relationship between Student and Course.',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[{"name":"enrolls_in","entity_a":"Student","entity_b":"Course","cardinality":"M:N","participation":"partial"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"relationship_match","required_relationships":[{"entity_a":"Student","entity_b":"Course","cardinality":"M:N"}]}',
 '{"hints":["M:N means both sides can have multiple counterparts","M:N relationships require a junction/bridge table when implemented"]}',
 '{"type":"er_diagram","tool":"relationship_connector"}',
 '{"topic":"many_to_many","bloom_level":"understand"}'),

-- ── Task ERD_004 ─────────────────────────────────────────────────────────────
('ERD_004',
 'Add a junction table for enrollment',
 'er_diagram', 'medium',
 4, 2, 21, 4,
 'published', true, 180,
 'Resolve the many-to-many relationship between Student and Course by adding an Enrollment entity. Enrollment should store enrollment_id, student_id (FK), and course_id (FK).',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Enrollment","attributes":[{"name":"enrollment_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"course_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false}]}],"relationships":[{"name":"has_enrollment","entity_a":"Student","entity_b":"Enrollment","cardinality":"1:N","participation":"partial"},{"name":"has_enrollment","entity_a":"Course","entity_b":"Enrollment","cardinality":"1:N","participation":"partial"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"entity_match","required_entities":["Student","Course","Enrollment"],"check_foreign_keys":true,"required_fks":[{"entity":"Enrollment","fk":"student_id","references":"Student"},{"entity":"Enrollment","fk":"course_id","references":"Course"}]}',
 '{"hints":["A junction table has two foreign keys pointing to the two original tables","It turns M:N into two 1:N relationships"]}',
 '{"type":"er_diagram","tool":"drag_and_drop_entity"}',
 '{"topic":"junction_table","bloom_level":"apply"}'),

-- ── Task ERD_005 ─────────────────────────────────────────────────────────────
('ERD_005',
 'Identify cardinality: student and submissions',
 'er_diagram', 'easy',
 4, 1, 21, 4,
 'published', true, 120,
 'A student can make many submissions, but each submission belongs to exactly one student. What is the cardinality of the relationship between Student and Submission?',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false}]},{"name":"Submission","attributes":[{"name":"submission_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false}]}],"relationships":[{"name":"submits","entity_a":"Student","entity_b":"Submission","cardinality":"1:N","participation":"partial"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"cardinality_match","required_cardinality":"1:N","entity_a":"Student","entity_b":"Submission"}',
 '{"hints":["Ask: can one student make many submissions? (yes) Can one submission belong to many students? (no)"]}',
 '{"type":"er_diagram","tool":"cardinality_selector"}',
 '{"topic":"cardinality_identification","bloom_level":"understand"}'),

-- ── Task ERD_006 ─────────────────────────────────────────────────────────────
('ERD_006',
 'Normalize: remove repeating groups',
 'er_diagram', 'medium',
 4, 2, 22, 4,
 'published', true, 180,
 'A table StudentCourses has columns: student_id, name, course1_name, course2_name, course3_name. This violates 1NF. Redesign it into two normalized tables.',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"StudentCourse","attributes":[{"name":"student_course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[{"name":"has_courses","entity_a":"Student","entity_b":"StudentCourse","cardinality":"1:N","participation":"total"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"normalization_check","violation":"repeating_groups","expected_normal_form":"1NF","required_entities":["Student","StudentCourse"]}',
 '{"hints":["1NF: each cell should hold one value, not a list","Create a new row for each course instead of new columns"]}',
 '{"type":"er_diagram","tool":"normalization_designer"}',
 '{"topic":"first_normal_form","bloom_level":"analyze"}'),

-- ── Task ERD_007 ─────────────────────────────────────────────────────────────
('ERD_007',
 'Identify partial functional dependency',
 'er_diagram', 'medium',
 4, 2, 22, 4,
 'published', true, 180,
 'A table Submission has composite PK (student_id, assignment_id) and also stores student_name. Student_name depends only on student_id, not the full PK. What normal form violation is this?',
 '{"entities":[{"name":"Submission","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":true,"nullable":false},{"name":"assignment_id","type":"INT","is_pk":true,"is_fk":true,"nullable":false},{"name":"student_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false,"violation":"partial_dependency"}]},{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[{"name":"submits","entity_a":"Student","entity_b":"Submission","cardinality":"1:N","participation":"partial"}],"normal_form_violation":"2NF","resolution":"move_student_name_to_Student_table"}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"violation_identification","expected_violation":"partial_dependency","expected_normal_form_violated":"2NF"}',
 '{"hints":["2NF: every non-key attribute must depend on the whole composite key","student_name depends only on student_id → partial dependency"]}',
 '{"type":"er_diagram","tool":"dependency_analyzer"}',
 '{"topic":"second_normal_form","bloom_level":"analyze"}'),

-- ── Task ERD_008 ─────────────────────────────────────────────────────────────
('ERD_008',
 'Design ER for assignment submission tracking',
 'er_diagram', 'medium',
 4, 2, 20, 4,
 'published', true, 180,
 'Design an ER diagram for a system where: Students submit Assignments. Each Assignment belongs to one Course. A Student can submit an Assignment only once. Include all entities, attributes, and relationships.',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"grade_level","type":"INT","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Assignment","attributes":[{"name":"assignment_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"title","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"max_score","type":"NUMERIC","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Submission","attributes":[{"name":"submission_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"assignment_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"score","type":"NUMERIC","is_pk":false,"is_fk":false,"nullable":true}]}],"relationships":[{"name":"belongs_to","entity_a":"Assignment","entity_b":"Course","cardinality":"N:1","participation":"total"},{"name":"makes","entity_a":"Student","entity_b":"Submission","cardinality":"1:N","participation":"partial"},{"name":"for","entity_a":"Submission","entity_b":"Assignment","cardinality":"N:1","participation":"total"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"full_er_match","required_entities":["Student","Course","Assignment","Submission"],"required_relationships":3,"check_foreign_keys":true}',
 '{"hints":["Submission links Student and Assignment — it acts like a junction table","One submission per student per assignment means unique(student_id, assignment_id) in Submission"]}',
 '{"type":"er_diagram","tool":"full_er_designer"}',
 '{"topic":"full_er_design","bloom_level":"apply"}'),

-- ── Task ERD_009 ─────────────────────────────────────────────────────────────
('ERD_009',
 'Identify transitive dependency (3NF)',
 'er_diagram', 'hard',
 4, 3, 22, 4,
 'published', true, 300,
 'A table Enrollment has: enrollment_id (PK), student_id, course_id, teacher_id, teacher_name. Teacher_name depends on teacher_id which depends on course_id. What normal form is violated and how do you fix it?',
 '{"entities":[{"name":"Enrollment","attributes":[{"name":"enrollment_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"course_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false}]},{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"teacher_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false}]},{"name":"Teacher","attributes":[{"name":"teacher_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"teacher_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[{"name":"taught_by","entity_a":"Course","entity_b":"Teacher","cardinality":"N:1","participation":"total"}],"normal_form_violation":"3NF","resolution":"extract_Teacher_entity"}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"violation_identification","expected_violation":"transitive_dependency","expected_normal_form_violated":"3NF","expected_resolution":"extract_Teacher_entity"}',
 '{"hints":["3NF: non-key attributes must not depend on other non-key attributes","teacher_name → teacher_id → course_id: this is a transitive chain","Fix: create a Teacher table"]}',
 '{"type":"er_diagram","tool":"dependency_analyzer"}',
 '{"topic":"third_normal_form","bloom_level":"analyze"}'),

-- ── Task ERD_010 ─────────────────────────────────────────────────────────────
('ERD_010',
 'Full school ER diagram with normalization',
 'er_diagram', 'hard',
 4, 3, 23, 4,
 'published', true, 300,
 'Design a fully normalized (3NF) ER diagram for a school system with: Students, Teachers, Courses (each taught by one teacher), Enrollments (student-course M:N), Assignments (per course), and Submissions (student submits assignment). Include all PKs, FKs, and relationships.',
 '{"entities":[{"name":"Student","attributes":[{"name":"student_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"grade_level","type":"INT","is_pk":false,"is_fk":false,"nullable":false},{"name":"class_section","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":true}]},{"name":"Teacher","attributes":[{"name":"teacher_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"teacher_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Course","attributes":[{"name":"course_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_name","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"teacher_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false}]},{"name":"Enrollment","attributes":[{"name":"enrollment_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"course_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"enrolled_at","type":"TIMESTAMP","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Assignment","attributes":[{"name":"assignment_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"course_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"title","type":"VARCHAR","is_pk":false,"is_fk":false,"nullable":false},{"name":"max_score","type":"NUMERIC","is_pk":false,"is_fk":false,"nullable":false}]},{"name":"Submission","attributes":[{"name":"submission_id","type":"INT","is_pk":true,"is_fk":false,"nullable":false},{"name":"student_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"assignment_id","type":"INT","is_pk":false,"is_fk":true,"nullable":false},{"name":"score","type":"NUMERIC","is_pk":false,"is_fk":false,"nullable":true},{"name":"submitted_at","type":"TIMESTAMP","is_pk":false,"is_fk":false,"nullable":false}]}],"relationships":[{"name":"teaches","entity_a":"Teacher","entity_b":"Course","cardinality":"1:N","participation":"total"},{"name":"enrolls_in","entity_a":"Student","entity_b":"Enrollment","cardinality":"1:N","participation":"partial"},{"name":"has_enrollment","entity_a":"Course","entity_b":"Enrollment","cardinality":"1:N","participation":"partial"},{"name":"has_assignments","entity_a":"Course","entity_b":"Assignment","cardinality":"1:N","participation":"total"},{"name":"submits","entity_a":"Student","entity_b":"Submission","cardinality":"1:N","participation":"partial"},{"name":"for_assignment","entity_a":"Submission","entity_b":"Assignment","cardinality":"N:1","participation":"total"}]}',
 '{}',
 '{}',
 '{}',
 '{"check_type":"full_er_match","required_entities":["Student","Teacher","Course","Enrollment","Assignment","Submission"],"required_relationships":6,"check_3nf":true}',
 '{"hints":["Start with the entities, then add relationships","Resolve M:N with a junction table (Enrollment)","Each FK lives in the many-side or child table"]}',
 '{"type":"er_diagram","tool":"full_er_designer"}',
 '{"topic":"full_normalized_er","bloom_level":"create"}')

on conflict (task_code) do update set
  task_title              = excluded.task_title,
  task_type               = excluded.task_type,
  difficulty_level        = excluded.difficulty_level,
  task_type_id            = excluded.task_type_id,
  difficulty_level_id     = excluded.difficulty_level_id,
  skill_area_id           = excluded.skill_area_id,
  task_status_id          = excluded.task_status_id,
  task_status             = excluded.task_status,
  is_active               = excluded.is_active,
  estimated_time_seconds  = excluded.estimated_time_seconds,
  instruction_text        = excluded.instruction_text,
  expected_er_model_json  = excluded.expected_er_model_json,
  database_schema_json    = excluded.database_schema_json,
  sample_data_json        = excluded.sample_data_json,
  expected_output_json    = excluded.expected_output_json,
  grading_rules_json      = excluded.grading_rules_json,
  hint_json               = excluded.hint_json,
  answer_format_json      = excluded.answer_format_json,
  metadata_json           = excluded.metadata_json,
  updated_at              = now();
